# main page logo
main:
  logo:
    dark: "/src/assets/images/worddancer.joycelanterman.com/main-logo.png"
    light: "/src/assets/images/worddancer.joycelanterman.com/main-logo.png"
    alt: "Dances with Words - Joyce Lanterman"

# navbar setup
navbar:
    # navbar logo setup
    logo:
      dark: "/src/assets/images/worddancer.joycelanterman.com/nav-logo-dark.png"
      light: "/src/assets/images/worddancer.joycelanterman.com/nav-logo-light.png"
      alt: "Dances with Words - Joyce Lanterman"
    left:
      -
        href: "/esl-teaching-materials"
        label: "ESL Teaching Materials"
      -
        href: "/us-civics-and-history"
        label: "US Civics and History"
      -
        href: "/academic-work"
        label: "Academic Work"
    right:
      -
        href: "/contact-us"
        label: "Contact Me"
    breadcrumbs:
      include: true
      valid_breadcrumbs:
        - href: "[slug]"
          label: "[slug]"
  #      - "[...page]"
        - href: "archive"
          label: "archive"
        - href: "french-instructional-video"
          label: "french instructional video"

# blog path (can be posts or blog)
# posts = src/assets/posts/...
# blog = src/assets/blog/...
blog:
  pagination_size: 10
  path: posts
  prefix: blog/

# footer setup
footer:
    content:
        - "Dances with Words and its logo are trademarks of Joyce Lanterman."
        - "All content © 2005-[CURRENT_YEAR] by Joyce Lanterman."

# include bluesky
bluesky:
    include: false
    hashtag_link: /categories/#[HASHTAG]

# tag/category information
tags_and_categories:
    aliases:
        machine-learning:
            - ml
        artificial-intelligence:
            - ai
        large-language-model:
            - llm
        reinforcement-learning:
            - rl
search:
  include: true

rss:
  include: true
  site:
    name: hiivelabs Blog
    description: A blog about ML, AI, Gamedev and other random stuff that crosses my mind.

# git remote add other-repo git@github.com:xxx/other-repo.git # or use a path like ../foo if you have it locally on your machine
# git remote add source ../hiivelabs.com

# git fetch source
# git merge source/astro --allow-unrelated-histories

# for file in *.md; do mv "$file" "${file%.md}.mdx"; done
